### ISSUE TITLE
Should Cz contain column(s) of zeros when nx > n1?

### ISSUE THREAD

**Issue by hongweimao** [ShanechiLab/PSID#2]
Hi @OmidS,

According to equation 4 of Sani et al. 2021, columns in Cz which correspond to the behavior irrelevant states (if exist) should be all zeros. 

In Example 2 (PSID/example/example.m, line 77), however, idSys2.Cz does not have those zero columns. If I understand correctly, there should be 2 (= nx - n1) columns of zeros in Cz because nx = 4 and n1 = 2 in this example.

If there is anything I missed, could you kindly point it out for me?

Btw, I was running example.m with Matlab R2021b.

Thank you,
Hongwei

**Comment by OmidS** [comment]
Hi Hongwei,

Thanks for the great question. In the simulation shown in the example, the second part of Cz (we will call it Cz2) converges toward 0 if you increase the number of training samples, which you can do by modifying the following line: 

https://github.com/ShanechiLab/PSID/blob/30d588e3e3ce800842d7fffa89314328fbf909e4/example/example.m#L22

But this only happens because here n1 is selected as the true number of behaviorally relevant states, which in this simulation is 2. If you use a smaller n1 (e.g. n1=0), then the Cz2 should not and will not converge to zero. Since in general the n1 that the user choses may not perfectly match the data, in PSID we learn all of Cz, including the second part (i.e. Cz2) from the data rather than forcing it to be zero (see equation 33 in the Supplementary Note 1 in the [PSID paper](https://rdcu.be/b993t)). This will result in an accurate model for the data even if the n1 that is chosen by the user is too small.

As an aside, I should also note that the value of Cz cannot be interpreted in isolation, because one could write equivalent models with different ranges of values in the latent state that would have different Cz values but give the exact same z. For example, making some dimensions of the latent states 10 times larger and the corresponding dimensions of Cz and Cy 10 times smaller wouldn't change the model (see Supplementary Note 3 on similarity transforms in the [PSID paper](https://rdcu.be/b993t)). So simply checking whether Cz2 is close to zero is not enough to show that it converges to 0. You can instead look at the covariance of z that comes from Cz2, or diag(Cz2 * x2Cov * Cz2'), where x2Cov is the covariance of the last nx-n1 dimensions in the estimated states (for this simulation: x2Cov = cov(xTestPred2(:, 3:end))). This is a quantity that is preserved under similarity transforms and is expected to converge to 0.

I hope this helps.
Omid

**Comment by hongweimao** [comment]
Hi Omid,

It makes a lot of sense to me. By increasing the number of training samples, I did get both Cz2 and the covariance of z that came from Cz2 converged towards 0, given the fact that the true number of behaviorally relevant states was assigned to n1. If the chosen n1 value was too small, Cz2 would explain a non-negligible portion of the variance of z.

Thanks a lot for the explanation. It really helps!
 
Hongwei
